-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_test]
import Aeneas
open Aeneas.Std
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace aeneas_test

/- [core::fmt::Arguments]
   Source: '/rustc/library/core/src/fmt/mod.rs', lines 319:0-319:24
   Name pattern: core::fmt::Arguments -/
axiom core.fmt.Arguments : Type

/- [core::fmt::{core::fmt::Arguments<'a>}#2::new_const]:
   Source: '/rustc/library/core/src/fmt/mod.rs', lines 337:4-337:81
   Name pattern: core::fmt::{core::fmt::Arguments<''a>}::new_const -/
axiom core.fmt.Arguments.new_const
  {N : Usize} : Array Str N → Result core.fmt.Arguments

/- [std::io::stdio::_print]:
   Source: '/rustc/library/std/src/io/stdio.rs', lines 1231:0-1231:39
   Name pattern: std::io::stdio::_print -/
axiom std.io.stdio._print : core.fmt.Arguments → Result Unit

/- [aeneas_test::main]:
   Source: 'src/main.rs', lines 1:0-3:1 -/
def main : Result Unit :=
  sorry

end aeneas_test
